trigger:
- main

resources:
- repo: self

variables:
- group: k8s
- name: dockerRegistryServiceConnection
  value: 'f0549fdc-9665-4b57-bdac-cc4d6199b174'
- name: containerRegistry
  value: '$[variables.container]'
- name: imagePullSecret
  value: '$[variables.pullSecret]'
- name: kubernetesServiceConnection
  value: '$[variables.serviceConnection]'
- name: dockerRegistryEndpoint
  value: '$[variables.registryEndpoint]'
- name: tag
  value: '$(Build.BuildId)'  
- name: imageGatewayRepository
  value: 'api_gateway'
- name: imageAuthRepository
  value: 'authentication_api'
- name: dockerfileGatewayPath
  value: '$(Build.SourcesDirectory)/src/OcelotApiGateway/Dockerfile'
- name: dockerfileAuthPath
  value: '$(Build.SourcesDirectory)/src/ApiAuthentication/Dockerfile'
  # Agent VM image name
- name: vmImageName
  value: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build Image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and publish '$(imageGatewayRepository)' image to Azure Container Registry
      inputs:
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: '$(imageGatewayRepository)'
        command: 'buildAndPush'
        Dockerfile: $(dockerfileGatewayPath)
        tags: |
          $(tag)
    - task: Docker@2
      displayName: Build and publish '$(imageAuthRepository)' image to Azure Container Registry
      inputs:
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: '$(imageAuthRepository)'
        command: 'buildAndPush'
        Dockerfile: $(dockerfileAuthPath)
        tags: |
          $(tag)
    - task: PublishPipelineArtifact@1
      displayName: Publish Pipeline Artifact
      inputs:
        artifactName: 'manifests'
        path: 'manifests'

- stage: Deploy
  displayName: Deploy to Prod
  dependsOn: Build
  variables:
    acrsecret: $(imagePullSecret)
  jobs:
  - job: Deploy
    displayName: Deploy to AKS
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        artifactName: 'manifests'
        targetPath: '$(System.ArtifactsDirectory)/manifests'
    - task: KubernetesManifest@1
      inputs:
        action: 'createSecret'
        connectionType: 'kubernetesServiceConnection'
        kubernetesServiceConnection: $(kubernetesServiceConnection)
        namespace: 'default'
        secretType: 'dockerRegistry'
        secretName: '$(acrsecret)'
        dockerRegistryEndpoint: $(dockerRegistryEndpoint)
    - task: KubernetesManifest@1
      displayName: Deploy to Kubernetes cluster      
      inputs:
        action: deploy
        namespace: 'default'
        connectionType: 'kubernetesServiceConnection'
        kubernetesServiceConnection: $(kubernetesServiceConnection)
        manifests: |
          $(System.ArtifactsDirectory)/k8s/deployment.yml
          $(System.ArtifactsDirectory)/k8s/service.yml
        containers: |
          $(containerRegistry)/$(imageGatewayRepository):$(tag)
          $(containerRegistry)/$(imageAuthRepository):$(tag)
        imagePullSecrets: |
          $(imagePullSecret)