trigger:
- main

resources:
- repo: self

variables:

  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'f0549fdc-9665-4b57-bdac-cc4d6199b174'
  imageRepository: 'apigateway'
  containerRegistry: 'testazcr.azurecr.io'
  dockerfilePath: '**/Dockerfile'  
  # dockerfilePath: '$(Build.SourcesDirectory)/src/OcelotApiGateway/Dockerfile'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'testazcr6f3c-auth'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'


stages:
- stage: Build
  displayName: Build Image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and publish image to Azure Container Registry
      inputs:
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: '$(imageRepository)'
        command: 'buildAndPush'
        Dockerfile: $(dockerfilePath)
        tags: |
          $(tag)
    - task: PublishPipelineArtifact@1
      inputs:
        artifactName: 'manifests'
        path: 'manifests'

- stage: Deploy
  displayName: Deploy to Dev
  dependsOn: Build
  variables:
    acrsecret: $(imagePullSecret)
  jobs:
  - job: Deploy
    displayName: Deploy to AKS
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        artifactName: 'manifests'
        targetPath: '$(System.ArtifactsDirectory)/manifests'
    - task: KubernetesManifest@1
      inputs:
        action: 'createSecret'
        connectionType: 'kubernetesServiceConnection'
        kubernetesServiceConnection: 'test-aks-default'
        namespace: 'default'
        secretType: 'dockerRegistry'
        secretName: '$(acrsecret)'
        dockerRegistryEndpoint: 'testazcr'
    - task: KubernetesManifest@1
      displayName: Deploy to Kubernetes cluster      
      inputs:
        action: deploy
        namespace: 'default'
        connectionType: 'kubernetesServiceConnection'
        kubernetesServiceConnection: 'test-aks-default'
        manifests: |
          $(System.ArtifactsDirectory)/manifests/deployment.yml
          $(System.ArtifactsDirectory)/manifests/service.yml
        containers: '$(containerRegistry)/$(imageRepository):$(tag)'
        imagePullSecrets: '$(imagePullSecret)'