services:

  api-gateway:
    image: ${DOCKER_REGISTRY-}api.gateway:v1
    # image: jeansagaz/api.gateway:v1
    container_name: api-gateway
    build:
      context: .
      dockerfile: /src/OcelotApiGateway/Dockerfile
      # dockerfile: ./src/OcelotApiGateway/Dockerfile
    # restart: unless-stopped
    ports:
      - "5003:8080"
    environment:
      - TZ=America/Sao_Paulo
      - ASPNETCORE_ENVIRONMENT=Docker
      # - ASPNETCORE_ENVIRONMENT=Production
      # - ASPNETCORE_URLS=http://+:7195
    networks:
      - api-gateway-network

  article-api:
    # hostname: api-article
    image: ${DOCKER_REGISTRY-}api.article:v1
    # image: jeansagaz/api.article:v1
    container_name: article-api
    build:
      context: .
      dockerfile: /src/ApiArticle/Dockerfile
      # dockerfile: ./src/ApiArticle/Dockerfile
    # restart: unless-stopped
    ports:
      - "5001:8080"
    environment:
      - TZ=America/Sao_Paulo
      - ASPNETCORE_ENVIRONMENT=Docker
      # - ASPNETCORE_ENVIRONMENT=Production
      # - ASPNETCORE_URLS=http://+:7195
    networks:
      - api-gateway-network

  writter-api:
    # hostname: api-writter
    image: ${DOCKER_REGISTRY-}api.writter:v1
    # image: jeansagaz/api.writter:v1
    container_name: writter-api
    build:
      context: .
      dockerfile: /src/ApiWritter/Dockerfile
      # dockerfile: ./src/ApiWritter/Dockerfile
    # restart: unless-stopped
    ports:
      - "5002:8080"
    environment:
      - TZ=America/Sao_Paulo
      - ASPNETCORE_ENVIRONMENT=Docker
      # - ASPNETCORE_ENVIRONMENT=Production
      # - ASPNETCORE_URLS=http://+:7195
    networks:
      - api-gateway-network

networks:
    api-gateway-network: 
      external: true