apiVersion : apps/v1
kind: Deployment
metadata:
  name: apiGateway 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apiGateway
  template:
    metadata:
      labels:
        app: apiGateway
    spec:
      containers:
        - name: api_gateway 
          image: testazcr.azurecr.io/api_gateway
          ports:
          - containerPort: 8080
          env: 
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"