apiVersion : apps/v1
kind: Deployment
metadata:
  name: apigateway 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apigateway
  template:
    metadata:
      labels:
        app: apigateway
    spec:
      containers:
        - name: apigateway 
          image: testazcr.azurecr.io/api_gateway
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "1Gi"
              cpu: "750m"
          env: 
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
---
apiVersion : apps/v1
kind: Deployment
metadata:
  name: authenticationapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authenticationapi
  template:
    metadata:
      labels:
        app: authenticationapi
    spec:
      containers:
        - name: authenticationapi 
          image: testazcr.azurecr.io/authentication_api
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "1Gi"
              cpu: "750m"
          env: 
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"