apiVersion: v1
kind: Service
metadata:
    name: apigateway
spec:
    type: LoadBalancer
    ports:
        - port: 8080 
    selector:
        app: apigateway
---
apiVersion: v1
kind: Service
metadata:
    name: authenticationapi
spec:
    type: ClusterIP
    ports:
        - port: 8081 
          targetPort: 8080
    selector:
        app: authenticationapi
