apiVersion: v1
kind: Service
metadata:
    name: authenticationapi
spec:
    type: LoadBalancer
    ports:
        - port: 8081 
          targetPort: 8080
    selector:
        app: authenticationapi